version: "3.3"

services:
  app:
    build: .
    ports: 
      - "3000:3000"
    image: api-server
    container_name: api-server
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    environment: 
      - SERVER_PORT=3000


  